name: My-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: xdebug
      - name: Inastall
        run: make install
      - name: Run Linter
        run: make lint
      - name: Run test
        run: make test
#      - name: Run test & publish code coverage
#        uses: paambaati/codeclimate-action@v2.6.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMAT }}
#        with:
#          coverageCommand: make test-coverage
#          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
#          debug: true
  coverage:
    name: Run test & publish code coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMAT }}
      with:
        coverageCommand: make test-coverage
